services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: order-processing-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:-Thiago@123}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q ''SELECT 1'' -No -C || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: src/OrderProcessing.API/Dockerfile
    container_name: order-processing-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=OrderProcessingDb;User Id=sa;Password=${MSSQL_SA_PASSWORD:-Thiago@123};TrustServerCertificate=True;"
    ports:
      - "3033:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sqlserver_data:
